export const TOOLS = {
  PENCIL: 'PENCIL',
  ERASER: 'ERASER',
  TEXT: 'TEXT',
  SIZE_TOOL: 'SIZE_TOOL',
  COLOR_TOOL: 'COLOR_TOOL',
  SQUARE: 'SQUARE',
  SEGMENT: 'SEGMENT',
  POINTER: 'POINTER',
  ARROW: 'ARROW',
  CIRCLE: 'CIRCLE',
  BUCKET: 'BUCKET',
  UNDO: 'UNDO',
  REDO: 'REDO',
  TRANSPARENCY: 'TRANSPARENCY',
  TRASH: 'TRASH',
  PAGE_LEFT: 'PAGE_LEFT',
  PAGE_RIGHT: 'PAGE_RIGHT',
  LOCK: 'LOCK',
  CURVED_ARROW: 'CURVED_ARROW',
  BLUR: 'BLUR',
  ZOOMIN: 'ZOOMIN',
  ZOOMOUT: 'ZOOMOUT',
  HAND: 'HAND'
};

export const SHAPE_TYPES = {
  PENCIL: 'PENCIL',
  ERASER: 'ERASER',
  TEXT: 'TEXT',
  SIZE_TOOL: 'SIZE_TOOL',
  COLOR_TOOL: 'COLOR_TOOL',
  SQUARE: 'SQUARE',
  SEGMENT: 'SEGMENT',
  POINTER: 'POINTER',
  ARROW: 'ARROW',
  CIRCLE: 'CIRCLE',
  IMAGE: 'IMAGE',
  CURVED_ARROW: 'CURVED_ARROW'
};

export const Sizes = {
  SIZE_1: 1,
  SIZE_2: 3,
  SIZE_3: 7,
  SIZE_4: 12,
  SIZE_5: 18,
  SIZE_6: 25,
  SIZE_7: 33,
  SIZE_8: 42
};
